### ISSUE TITLE
Failure While Initialising Payment

### ISSUE THREAD

**Issue by sheinfeld** [michelmelo/laravel-easypay#2]
Hi Michel,

Upon trying to start a payment I get:

`MichelMelo\EasyPay\EasyPayException {#1525 ▼
  #message: "error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure"
  #code: 35
  #file: "/var/www/vhosts/standocasiao.pt/Ocasiao-CMS/vendor/michelmelo/laravel-easypay/src/EasyPayClient.php"
  #line: 123
  trace: {▶}
}`

Do you know how to solve this?

Regards.

**Comment by michelmelo** [comment]
Desculpa,
o projecto ficou parado, :(
